module.exports = {
    CREATE: "CREATE",
    UPDATE: "UPDATE",
    DELETE: "DELETE",
    TRANSFER_AVAILABLE_FROM: "TRANSFER_AVAILABLE_FROM",
    TRANSFER_AVAILABLE_TO: "TRANSFER_AVAILABLE_TO",
    TRANSFER_LOCKED_FROM: "TRANSFER_LOCKED",
    TRANSFER_LOCKED_TO: "TRANSFER_LOCKED",
    TRANSFER_AVAILABLE: "TRANSFER_AVAILABLE",
    TRANSFER_LOCKED: "TRANSFER_LOCKED",
    LOCK: "LOCK",
    UNLOCK: "UNLOCK",
    MINT: "MINT",
    REWARD: "REWARD",
    CONFISCATE_LOCKED: "CONFISCATE_LOCKED",
    CREATE_OBJECT: "CREATE_OBJECT",
    LOGIN: "LOGIN",
    PASSKEY_REGISTER: "PASSKEY_REGISTER"
}
